[[private-pypi]]
distrib = "private-pypi"
package = "private_pypi-0.1.1-py3-none-any"
ext = "whl"
sha256 = "32478425ceeb0a552ce4b57c77a65dcfc51f56ac6ec04afff1c80becd5e38a9e"
type = "github"
url = "https://api.github.com/repos/private-pypi-test-org/create-repo-debug-18/releases/assets/18071366"

[private-pypi.meta]
name = "private-pypi"
version = "0.1.1"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = "A private PyPI server powered by backend(s) like GitHub."
home_page = "https://github.com/private-pypi/private-pypi"
author = "huntzhan"
author_email = "huntzhan.dev@gmail.com"
maintainer = ""
maintainer_email = ""
license = "MIT"
description = "# Private-PyPI: A private PyPI server powered by backend(s) like GitHub\n\n## CLI\n\n`private_pypi_server`:\n\n```txt\nRun the private-pypi server.\n\nSYNOPSIS\n    private_pypi_server CONFIG ROOT <flags>\n\nPOSITIONAL ARGUMENTS\n    CONFIG (str):\n        Path to the package repositories config.\n    ROOT (str):\n        Path to the root folder.\n\nFLAGS\n    --admin_secret (Optional[str]):\n        Path to the admin secrets config with read/write permission.\n        This field is required for local index synchronization.\n        Defaults to None.\n    --auth_read_expires (int):\n        The expiration time (in seconds) for read authentication.\n        Defaults to 3600.\n    --auth_write_expires (int):\n        The expiration time (in seconds) for write authentication.\n        Defaults to 300.\n    --extra_index_url (str):\n        Extra index url for redirection in case package not found.\n        If set to empty string explicitly redirection will be suppressed.\n        Defaults to 'https://pypi.org/simple/'.\n    --debug (bool):\n        Enable debug mode.\n        Defaults to False.\n    --host (str):\n        The interface to bind to.\n        Defaults to 'localhost'.\n    --port (int):\n        The port to bind to.\n        Defaults to 8080.\n    **waitress_options (Dict[str, Any]):\n        Optional arguments that `waitress.serve` takes.\n        Details in https://docs.pylonsproject.org/projects/waitress/en/stable/arguments.html.\n        Defaults to {}.\n```\n"
keywords = "private,pypi,github,packaging,dependency"
classifiers = "License :: OSI Approved :: MIT License"
download_url = ""
comment = ""
md5_digest = "a31d2fe3e0c075dbdaac37ecbcb38ed5"
sha256_digest = "32478425ceeb0a552ce4b57c77a65dcfc51f56ac6ec04afff1c80becd5e38a9e"
blake2_256_digest = "bbb906f6963ad041c6a91bd706ee0fd766c19a5ef63123754fac9887265b957f"
project_urls = "Repository, https://github.com/private-pypi/private-pypi"
requires_dist = "requests (>=2.22.0,<3.0.0)"
requires_python = ">=3.7,<4.0"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "private-pypi"
sha256 = "32478425ceeb0a552ce4b57c77a65dcfc51f56ac6ec04afff1c80becd5e38a9e"
[[private-pypi]]
distrib = "private-pypi"
package = "private-pypi-0.1.1.tar"
ext = "gz"
sha256 = "b694ae5ab296c0f94a4aeb0e2b64684907af8b06cd5bc8d3a0b6f1c48a136c5a"
type = "github"
url = "https://api.github.com/repos/private-pypi-test-org/create-repo-debug-18/releases/assets/18071364"

[private-pypi.meta]
name = "private-pypi"
version = "0.1.1"
filetype = "sdist"
pyversion = ""
metadata_version = "2.1"
summary = "A private PyPI server powered by backend(s) like GitHub."
home_page = "https://github.com/private-pypi/private-pypi"
author = "huntzhan"
author_email = "huntzhan.dev@gmail.com"
maintainer = ""
maintainer_email = ""
license = "MIT"
description = "# Private-PyPI: A private PyPI server powered by backend(s) like GitHub\n\n## CLI\n\n`private_pypi_server`:\n\n```txt\nRun the private-pypi server.\n\nSYNOPSIS\n    private_pypi_server CONFIG ROOT <flags>\n\nPOSITIONAL ARGUMENTS\n    CONFIG (str):\n        Path to the package repositories config.\n    ROOT (str):\n        Path to the root folder.\n\nFLAGS\n    --admin_secret (Optional[str]):\n        Path to the admin secrets config with read/write permission.\n        This field is required for local index synchronization.\n        Defaults to None.\n    --auth_read_expires (int):\n        The expiration time (in seconds) for read authentication.\n        Defaults to 3600.\n    --auth_write_expires (int):\n        The expiration time (in seconds) for write authentication.\n        Defaults to 300.\n    --extra_index_url (str):\n        Extra index url for redirection in case package not found.\n        If set to empty string explicitly redirection will be suppressed.\n        Defaults to 'https://pypi.org/simple/'.\n    --debug (bool):\n        Enable debug mode.\n        Defaults to False.\n    --host (str):\n        The interface to bind to.\n        Defaults to 'localhost'.\n    --port (int):\n        The port to bind to.\n        Defaults to 8080.\n    **waitress_options (Dict[str, Any]):\n        Optional arguments that `waitress.serve` takes.\n        Details in https://docs.pylonsproject.org/projects/waitress/en/stable/arguments.html.\n        Defaults to {}.\n```\n"
keywords = "private,pypi,github,packaging,dependency"
classifiers = "License :: OSI Approved :: MIT License"
download_url = ""
comment = ""
md5_digest = "f9856f1e722ea9b89ebacc8fb4905b33"
sha256_digest = "b694ae5ab296c0f94a4aeb0e2b64684907af8b06cd5bc8d3a0b6f1c48a136c5a"
blake2_256_digest = "c3456f9a2a87c4a345d53c1f95da7855cbb03aab33e20016caa55e4edb899515"
project_urls = "Repository, https://github.com/private-pypi/private-pypi"
requires_dist = "requests (>=2.22.0,<3.0.0)"
requires_python = ">=3.7,<4.0"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "private-pypi"
sha256 = "b694ae5ab296c0f94a4aeb0e2b64684907af8b06cd5bc8d3a0b6f1c48a136c5a"
